### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by gvsrini** [nblock/jasperstarter#1]
Any instructions for installing on Ubuntu/Debian?

**Comment by nblock** [comment]
This is just a source package, you need to build it yourself before installing it:
```
git clone https://github.com/nblock/jasperstarter.git
cd jasperstarter
git checkout pristine-tar
git checkout upstream
git checkout master
gbp buildpackage -us -uc
sudo dpkg -i ../jasperstarter_3.1.10-1_all.deb
```
Please note:
* this package has not been updated for Jasperstarter 3.2 yet
* Git Buildpackage is required to build it
